specVersion: 1.0.0
name: avail-indexer
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  Avail indexer project
repository: "https://github.com/availproject/avail-indexer"
schema:
  file: ./schema.graphql
network:
  # The genesis hash of the network (hash of block 0)
  # chainId: "0x6f09966420b2608d1947ccfb0f2a362450d1fc7fd902c29b67c906eaa965a7ae" # Goldberg
  # chainId: "0x870e903076fe2bec249cc31fdb1b5717d89d0a0b6ae38241a58d6edeac5e1859" # Couscous
  # chainId: "<local_chain_genesis_hash>"                                         # Local
  # chainId: "<local_chain_genesis_hash>"                                         # Local with Docker
  # endpoint:
  #   ["wss://goldberg.avail.tools/ws"]
  #   ["wss://couscous-devnet.avail.tools/ws"]
  #   ["ws://127.0.0.1:9944"]                                                     # Local
  #   ["ws://host.docker.internal:9944"]                                          # Local with Docker
  
  # The genesis hash of the network (hash of block 0)
  chainId: "<blockhash>"
  endpoint:
    ["<ws-endpoint>"]
  chaintypes:
    file: ./types.json
  bypassBlocks: [272472, 272483, 272484, 272497] #Some blocks to bypass because of event errors
dataSources:
  - kind: substrate/Runtime
    startBlock: 0
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
