specVersion: 1.0.0
name: avail-indexer
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  Avail indexer project
repository: "https://github.com/availproject/avail-indexer"
schema:
  file: ./schema.graphql
network:
  # The genesis hash of the network (hash of block 0)
  # chainId: "0xd3d2f3a3495dc597434a99d7d449ebad6616db45e4e4f178f31cc6fa14378b70" # Turing
  # chainId: "0x6f09966420b2608d1947ccfb0f2a362450d1fc7fd902c29b67c906eaa965a7ae" # Goldberg
  # chainId: "<local_chain_genesis_hash>"                                         # Local
  # chainId: "<local_chain_genesis_hash>"                                         # Local with Docker
  # endpoint:
  #   ["wss://turing-rpc.avail.so"]                                               # Turing
  #   ["wss://goldberg.avail.tools/ws"]                                           # Goldberg
  #   ["ws://127.0.0.1:9944"]                                                     # Local
  #   ["ws://host.docker.internal:9944"]                                          # Local with Docker
  
  # The genesis hash of the network (hash of block 0)
  chainId: "<blockhash>"
  endpoint:
    ["<ws-endpoint>"]
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
